### ISSUE TITLE
Changes in Google Translator API (Maybe)

### ISSUE THREAD

**Issue by pouyacodes** [sienori/simple-translate#506]
Recently I tried to use the extension and It doesn't work. I wonder about the cause of this problem.
If you open the Console tab of the browser there is an error for the extension:

```
TypeError: e.terms is undefined (content.js)
```

Looks like the extension can not read ``terms`` property from ``e`` object. With a bit of search and exploration in the source code I realized that ``e`` object and ``terms`` come from Google Translate API and more specifically [``sendRequestToGoogle``](https://github.com/sienori/simple-translate/blob/b31d53e539516c8d7dd1574fd963710214dd963d/src/common/translate.js#L32C70-L32C70) function in the source code.

The extension uses [this](https://github.com/sienori/simple-translate/blob/b31d53e539516c8d7dd1574fd963710214dd963d/src/common/translate.js#L33) Google Translator API endpoint and populate the required field and then fetchs data. Then function tries to read some field like ``sentences`` which contains the translation(s) and ``dict`` for "word vocabulary" or something. 

Then I tried to send some random requests to this endpoint and check the result with code to make sure that the function read proper values from the data. For example:

```console
$ curl "https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=fa&dt=t&dt=bd&dj=1&q=Asked"
```
and the response is:

```json
{
  "sentences": [
    {
      "trans": "پرسیده شد",
      "orig": "Asked",
      "backend": 3,
      "model_specification": [
        {}
      ],
      "translation_engine_debug_info": [
        {
          "model_tracking": {
            "checkpoint_md5": "982c75c78c6c8e6005ec3a4021a7f785",
            "launch_doc": "tea_GrecoIndoEuropeA_en2elfahykakumksq_2021q3.md"
          }
        }
      ]
    }
  ],
  "dict": [
    {
      "pos": "adjective",
      "entry": [
        {
          "word": "خواسته",
          "reverse_translation": [
            "asked",
            "demanded",
            "requested",
            "wanted",
            "required",
            "desired"
          ],
          "score": 0.10215643
        }
      ],
      "base_form": "asked",
      "pos_enum": 3
    }
  ],
  "src": "en",
  "spell": {}
}
```

But there is no ``terms`` field in the result. So I think perhaps Google changes something in the API.

Also, my browser is Mozilla Firefox and the extension version that I use is ``2.8.1``.

Thanks!

**Comment by pouyacodes** [comment]
Thanks! :heart: Looks like works and the issue is resolved. :+1: 

Do I have to close the issue right now or wait until the next official release?

**Comment by ttrasn** [comment]
that file was a temporary fix, but the issue still exists until the changes are fixed. so it is better to wait.

**Comment by pouyacodes** [comment]
Yes. Thanks.

**Comment by sienori** [comment]
This seems to have been fixed by a change in Google's API. Simple Translate also fixed with https://github.com/sienori/simple-translate/pull/507.
